version = 0.1

[default.deploy.parameters]
stack_name = "sam-app-kandidat-27"
resolve_s3 = true
s3_prefix = "sam-app-kandidat-27"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"kandidat-27-data\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
